# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-14 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pics', models.ImageField(default=b'homepage/image/background.png', upload_to=b'')),
            ],
        ),
    ]
